[package]
name = "server"
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
bevy = { version = "=0.19.0", default-features = false, features = ["bevy_state", "bevy_log", "bevy_asset"] }
avian2d = { workspace = true, features = ["2d", "f32", "parry-f32"] }
tiled = { workspace = true }
bevy_replicon = { workspace = true }
bevy_replicon_renet = { workspace = true }
content = { path = "../content" }
game_core = { path = "../game_core" }
protocol = { path = "../protocol" }
rand = { workspace = true }
ron = { workspace = true }
serde = { workspace = true }
